services:
  utildeprecate:
    image: utildeprecate
    build:
      context: node_modules/util-deprecate
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
